version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    environment:
      NETWORK:
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
      - node-config:/nix/store
    restart: on-failure

  cardano-wallet:
    image: inputoutput/cardano-wallet:latest
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
      - node-config:/config
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ([[ $$NETWORK == \"testnet\" ]] && $$CMD --testnet /config/*testnet-genesis.json)
      "
    environment:
      CMD: "cardano-wallet-byron serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure

  icarus:
    image: piotrstachyra/icarus:latest
    network_mode: "host"
    restart: on-failure

volumes:
  node-mainnet-db:
  node-testnet-db:
  wallet-mainnet-db:
  wallet-testnet-db:
  node-ipc:
  node-config:
