version: "3.7"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    environment:
      - NETWORK=mainnet
    volumes:
      - config:/data
      - config:/ipc
    restart: on-failure

  cardano-wallet:
    image: inputoutput/cardano-wallet:latest
    volumes:
      - config:/config
    ports:
      - 8090:8090
    command: serve --mainnet --node-socket /config/node.socket --database /config/wallet-db --listen-address '0.0.0.0'
    restart: on-failure

  icarus:
    image: piotrstachyra/icarus:latest
    network_mode: "host"

volumes:
  config:
